name: Multi Job CI → Docker → Registries

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: portfolio

jobs:

  # =========================
  # 1️⃣ BUILD + TEST
  # =========================
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm install

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm test --if-present --watchAll=false

  # =========================
  # 2️⃣ DOCKER BUILD + SCAN
  # =========================
  docker-build-scan:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t portfolio:ci .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: portfolio:ci
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Save image artifact
        run: docker save portfolio:ci -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  # =========================
  # 3️⃣ PUSH REGISTRIES
  # =========================
  push-registries:
    needs: docker-build-scan
    runs-on: ubuntu-latest

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: docker load -i image.tar

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag images
        run: |
          docker tag portfolio:ci ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker tag portfolio:ci ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Push DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
